title: Matt Banks
description: thoughts on web development, tech, gaming, etc.

url: http://mattbanks.me
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mattbanks
   twitter: mattbanks
   facebook: mattbanks

google_analytics: "XXXXX"
