baseurl= "https://www.mattbanks.me"
LanguageCode= "en-US"
title= "Matt Banks"
paginate = 5
copyright = "All Rights Reserved"
canonifyurls = true
theme = "casper"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[permalinks]
  post = "/:slug"

[params]
  description = "thoughts on web development, tech, gaming, etc."
  metadescription = "thoughts on web development, tech, gaming, etc."
  cover = "images/santa-monica-pier.jpg"
  author = "Matt Banks"
  authorlocation = "Saratoga Springs, NY"
  authorwebsite = "https://www.mattbanks.me"
  authorbio= "Senior Engineer at Wolfjaw Studios. Formerly PUBG and MadGlory. JavaScript is fun. Manchester City, Yankees, and NYCFC  fan. I like games, coffee & craft beer."
  logo = "images/matt.jpg"
  googleAnalyticsUserID = "UA-27725430-1"
  githubName = "mattbanks"
  twitterName = "mattbanks"
  hideHUGOSupport = true

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "solarized-dark"

  customCSS = ["css/mattbanks.css"]

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = -120
[[menu.main]]
  name = "Github"
  url = "https://github.com/mattbanks"
  weight = 100
[[menu.main]]
  name = "Twitter"
  pre = "<h3>Follow me</h3>"
  url = "https://twitter.com/mattbanks"
  weight = 101
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 102
[[menu.main]]
  name = "About"
  pre = "<h3>About me</h3>"
  url = "/about"
  weight = 109
