[build]
publish = "public"
command = "npm run build"

[context.production.environment]
  NODE_VERSION = "18.12.1"
  NPM_VERSION = "9.2.0"

[context.deploy-preview.environment]
  NODE_VERSION = "18.12.1"
  NPM_VERSION = "9.2.0"
