[build]
publish = "public"
command = "gatsby build"

[context.production.environment]
  NODE_VERSION = "14.2.0"
  NPM_VERSION = "6.14.5"

[context.deploy-preview.environment]
  NODE_VERSION = "14.2.0"
  NPM_VERSION = "6.14.5"
