[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.55.5"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.5"
